ALTER TABLE orders ADD COLUMN delivery_type VARCHAR(20) NOT NULL DEFAULT 'DELIVERY' COMMENT '配送方式: DELIVERY-外卖配送, SELF_PICKUP-门店自提';
ALTER TABLE orders ADD COLUMN pickup_store VARCHAR(100) COMMENT '自提门店名称';
ALTER TABLE orders ADD COLUMN pickup_time DATETIME COMMENT '预计自提时间';
